<a href="https://colab.research.google.com/github/Aruneet-11/Fake_news_detection/blob/main/FAKE_NEWS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Fake news detection Project

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from google.colab import files
import re
import string

In [ ]:
df_fake=pd.read_csv('/content/Fake.csv')
df_true=pd.read_csv('/content/True.csv')

In [ ]:
df_fake.shape
df_fake.head(10)

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017"
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017"
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017"
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017"
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017"

In [ ]:
df_true.head(10)

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
5,"White House, Congress prepare for talks on spe...","WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...",politicsNews,"December 29, 2017"
6,"Trump says Russia probe will be fair, but time...","WEST PALM BEACH, Fla (Reuters) - President Don...",politicsNews,"December 29, 2017"
7,Factbox: Trump on Twitter (Dec 29) - Approval ...,The following statements were posted to the ve...,politicsNews,"December 29, 2017"
8,Trump on Twitter (Dec 28) - Global Warming,The following statements were posted to the ve...,politicsNews,"December 29, 2017"
9,Alabama official to certify Senator-elect Jone...,WASHINGTON (Reuters) - Alabama Secretary of St...,politicsNews,"December 28, 2017"

In [ ]:
df_fake['class']=0
df_true['class']=1

In [ ]:
print(df_fake.shape)
print(df_true.shape)

(23481, 5)
(21417, 5)

In [ ]:
df_fake_manual_testing=df_fake.tail(10)
for i in range(23480,23470,-1):
  df_fake.drop([i], axis=0, inplace=True)
df_true_manual_testing=df_true.tail(10)
for i in range(21416,21106,-1):
  df_true.drop([i], axis=0,inplace=True)

In [ ]:
df_manual_testing=pd.concat([df_fake_manual_testing,df_true_manual_testing],axis=0)
df_manual_testing.to_csv("manual_testing.csv")
files.download('manual_testing.csv')

Merging the datset i.e fake and true data.

In [ ]:
df_merge=pd.concat([df_fake,df_true],axis=0)
df_merge.head(20)

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017",0
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017",0
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017",0
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017",0
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017",0
10,"Papa John’s Founder Retires, Figures Out Raci...","A centerpiece of Donald Trump s campaign, and ...",News,"December 21, 2017",0
11,WATCH: Paul Ryan Just Told Us He Doesn’t Care...,Republicans are working overtime trying to sel...,News,"December 21, 2017",0
12,Bad News For Trump — Mitch McConnell Says No ...,Republicans have had seven years to come up wi...,News,"December 21, 2017",0
13,WATCH: Lindsey Graham Trashes Media For Portr...,The media has been talking all day about Trump...,News,"December 20, 2017",0
14,Heiress To Disney Empire Knows GOP Scammed Us...,Abigail Disney is an heiress with brass ovarie...,News,"December 20, 2017",0
15,Tone Deaf Trump: Congrats Rep. Scalise On Los...,Donald Trump just signed the GOP tax scam into...,News,"December 20, 2017",0
16,The Internet Brutally Mocks Disney’s New Trum...,A new animatronic figure in the Hall of Presid...,News,"December 19, 2017",0
17,Mueller Spokesman Just F-cked Up Donald Trump...,Trump supporters and the so-called president s...,News,"December 17, 2017",0
18,SNL Hilariously Mocks Accused Child Molester ...,"Right now, the whole world is looking at the s...",News,"December 17, 2017",0
19,Republican Senator Gets Dragged For Going Aft...,Senate Majority Whip John Cornyn (R-TX) though...,News,"December 16, 2017",0

In [ ]:
#removing the title,subject and data column from the datset.
df=df_merge.drop(['title','subject','date'], axis=1)
df.head(10)

                                                text  class
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0
5  The number of cases of cops brutalizing and ki...      0
6  Donald Trump spent a good portion of his day a...      0
7  In the wake of yet another court decision that...      0
8  Many people have raised the alarm regarding th...      0
9  Just when you might have thought we d get a br...      0

In [ ]:
#to shuffle the data.
df=df.sample(frac=1)
df.head(10)

                                                    text  class
18459  Judicial Watch today announced that the Nation...      0
20978  HANOI (Reuters) - Vietnam on Tuesday issued a ...      1
3679   On Saturday morning, Hillary Clinton s campaig...      0
18913  THE HUNTINGTON BEACH, CA RALLY WAS PRETTY BIG ...      0
13314  SANTO DOMINGO/CARACAS (Reuters) - Members of V...      1
15189  SHANGHAI (Reuters) - China s self-developed C9...      1
18588  VIENNA (Reuters) - Austria s Social Democratic...      1
8915   SARANDE, Albania (Reuters) - Whatever the outc...      1
4051   (Reuters) - North Korea’s latest display of it...      1
15862  BUDAPEST (Reuters) - Voter support for Hungary...      1

In [ ]:
#to check the null values in the dataframe
df.isnull().sum()

text     0
class    0
dtype: int64

In [ ]:
#to remove all the unnecessary words from the text.
def word_drop(text):
  text=text.lower()
  text=re.sub('\[.*?\]','',text)
  text=re.sub("\\W"," ",text)
  text=re.sub('https?://\S+|www\.\S+' ,' ', text)
  text=re.sub('<.*?>+', ' ',text)
  text=re.sub('[%s]' % re.escape(string.punctuation),' ',text)
  text=re.sub('\n',' ',text)
  text=re.sub('\w*\d\w*',' ',text)
  return text

In [ ]:
df['text']=df['text'].apply(word_drop)
df.head(10)

                                                    text  class
18459  judicial watch today announced that the nation...      0
20978  hanoi  reuters    vietnam on tuesday issued a ...      1
3679   on saturday morning  hillary clinton s campaig...      0
18913  the huntington beach  ca rally was pretty big ...      0
13314  santo domingo caracas  reuters    members of v...      1
15189  shanghai  reuters    china s self developed   ...      1
18588  vienna  reuters    austria s social democratic...      1
8915   sarande  albania  reuters    whatever the outc...      1
4051    reuters    north korea s latest display of it...      1
15862  budapest  reuters    voter support for hungary...      1

Define dependent and independent variables.

In [ ]:
x=df['text']
y=df['class']

In [ ]:
#training and testing of the data.
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
Vectorization=TfidfVectorizer()
xv_train=Vectorization.fit_transform(x_train)
xv_test=Vectorization.transform(x_test)

Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
LR.fit(xv_train,y_train)

LogisticRegression()

In [ ]:
#check the accuracy of the model
LR.score(xv_test,y_test)

0.9868102288021534

In [ ]:
#classification report 
pred_LR=LR.predict(xv_test)
print(classification_report(y_test,pred_LR))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5877
           1       0.99      0.99      0.99      5268

    accuracy                           0.99     11145
   macro avg       0.99      0.99      0.99     11145
weighted avg       0.99      0.99      0.99     11145

Making a Predictive System

In [ ]:
x_new=xv_test[107]
prediction=LR.predict(x_new)
print(prediction)
if prediction==1:
  print("True news")
else:
  print("Fake news")

[0]
Fake news